---
docker:
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/p4p docker
    - docker push $CI_REGISTRY_IMAGE/p4p
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
