---
version: '3'
services:
  p4p:
    image: registry.gitlab.com/yaegashi/p4p-docker/p4p
    environment:
      P4TARGET: perforce:1666
    volumes:
      - ./data:/data
    ports:
      - 127.0.0.1:1666:1666
