on: push
env:
  IMAGE: "docker.pkg.github.com/${{github.repository}}/p4p"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - run: docker login docker.pkg.github.com -u ${{github.repository_owner}} -p ${{github.token}}
      - run: docker build -t ${IMAGE} docker
      - run: docker push ${IMAGE}
