on:
  push:
    tags:
      - 'v*'
env:
  IMAGE: "ghcr.io/${{github.repository}}/p4p"
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - run: docker login ghcr.io -u ${{github.actor}} -p ${{secrets.PAT}}
      - run: echo "TAG=${GITHUB_REF#refs/*/}" >>$GITHUB_ENV
      - run: docker build -t ${IMAGE}:${TAG} docker
      - run: docker push ${IMAGE}:${TAG}
